# Generated by Django 5.2.17 on 2026-09-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('backend', 'Backend'), ('database', 'Database'), ('ai_data', 'AI & Data'), ('development_tools', 'Development Tools'), ('frontend', 'Frontend'), ('mobile', 'Mobile')], max_length=32)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'technologies',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=260)),
                ('detailed_description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='projects/thumbnails/')),
                ('featured_image', models.ImageField(blank=True, upload_to='projects/featured/')),
                ('category', models.CharField(blank=True, choices=[('web_application', 'Web Application'), ('ai_data', 'AI & Data'), ('mobile_application', 'Mobile Application'), ('research', 'Research'), ('other', 'Other')], max_length=32)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='projects.technology')),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
