# Generated by Django 5.2.17 on 2026-09-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technology_input',
            field=models.CharField(blank=True, help_text='Enter technologies separated by commas, e.g. Django, Python, PostgreSQL', max_length=500),
        ),
    ]
