# Generated by Django 5.2.17 on 2026-09-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('facebook', 'Facebook')], max_length=32)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('value', models.CharField(max_length=240)),
                ('icon', models.CharField(blank=True, max_length=120)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'contact information',
                'verbose_name_plural': 'contact information',
                'ordering': ['display_order', 'medium'],
            },
        ),
    ]
