# Generated by Django 5.2.17 on 2026-09-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='label',
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='icon',
            field=models.CharField(blank=True, help_text='Paste Font Awesome markup, for example: <i class="fa-regular fa-envelope"></i>', max_length=180),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='medium',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=32),
        ),
    ]
