# Generated by Django 5.2.17 on 2026-09-06 20:13

from datetime import date

from django.db import migrations
from django.utils.text import slugify


SKILLS = [
    ("Python", "programming"),
    ("SQL", "programming"),
    ("JavaScript", "programming"),
    ("Dart", "programming"),
    ("C/C++", "programming"),
    ("PHP", "programming"),
    ("Django", "backend"),
    ("FastAPI", "backend"),
    ("REST APIs", "backend"),
    ("Laravel", "backend"),
    ("PostgreSQL", "database"),
    ("MySQL", "database"),
    ("SQLite", "database"),
    ("Hive", "database"),
    ("Pandas", "ai_data"),
    ("NumPy", "ai_data"),
    ("TensorFlow", "ai_data"),
    ("Keras", "ai_data"),
    ("Scikit-learn", "ai_data"),
    ("LangGraph", "ai_data"),
    ("Matplotlib", "ai_data"),
    ("Flutter", "programming"),
    ("Git", "development_tools"),
    ("GitHub", "development_tools"),
    ("Jupyter", "development_tools"),
    ("Docker", "development_tools"),
]

PROJECT_TITLES = [
    "EventUp",
    "EduQuest",
    "DineEasy",
    "StayEase",
    "FitMeal",
    "BTC/USD LSTM",
    "Dairy Cattle Heat Detection by Dual-Camera YOLOv8 Ensemble",
]


def seed_initial_portfolio_data(apps, schema_editor):
    Skill = apps.get_model("core", "Skill")
    Project = apps.get_model("projects", "Project")
    Experience = apps.get_model("experience", "Experience")
    Education = apps.get_model("experience", "Education")

    for display_order, (name, category) in enumerate(SKILLS, start=1):
        Skill.objects.update_or_create(
            name=name,
            defaults={
                "category": category,
                "display_order": display_order,
            },
        )

    for display_order, title in enumerate(PROJECT_TITLES, start=1):
        Project.objects.update_or_create(
            slug=slugify(title),
            defaults={
                "title": title,
                "display_order": display_order,
                "published": False,
                "featured": False,
            },
        )

    Experience.objects.update_or_create(
        job_title="Research Engineer",
        company="AIMS Lab, United International University",
        start_date=date(2025, 8, 1),
        defaults={
            "employment_type": "part_time",
            "end_date": date(2025, 10, 1),
            "display_order": 1,
            "is_featured": False,
        },
    )

    Education.objects.update_or_create(
        institution="BRAC University",
        degree="B.Sc. in Computer Science",
        start_date=date(2022, 1, 1),
        defaults={
            "field": "Computer Science",
            "end_date": date(2026, 6, 1),
            "display_order": 1,
        },
    )


def unseed_initial_portfolio_data(apps, schema_editor):
    Skill = apps.get_model("core", "Skill")
    Project = apps.get_model("projects", "Project")
    Experience = apps.get_model("experience", "Experience")
    Education = apps.get_model("experience", "Education")

    Skill.objects.filter(name__in=[name for name, _category in SKILLS]).delete()
    Project.objects.filter(slug__in=[slugify(title) for title in PROJECT_TITLES]).delete()
    Experience.objects.filter(
        job_title="Research Engineer",
        company="AIMS Lab, United International University",
        start_date=date(2025, 8, 1),
    ).delete()
    Education.objects.filter(
        institution="BRAC University",
        degree="B.Sc. in Computer Science",
        start_date=date(2022, 1, 1),
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("projects", "0001_initial"),
        ("experience", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_initial_portfolio_data, unseed_initial_portfolio_data),
    ]
