# Generated by Django 5.2.17 on 2026-09-06 20:33

from django.db import migrations
from django.utils.text import slugify


PROJECT_TITLES = [
    "EventUp",
    "EduQuest",
    "DineEasy",
    "StayEase",
    "FitMeal",
    "BTC/USD LSTM",
    "Dairy Cattle Heat Detection by Dual-Camera YOLOv8 Ensemble",
]

RESPONSIBILITIES = "\n".join(
    [
        "Literature review",
        "Comparative analysis",
        "Research proposal development",
        "Research related to intelligent electricity demand forecasting and optimization",
    ]
)

RESEARCH_TITLE = "Dairy Cattle Heat Detection by Dual-Camera YOLOv8 Ensemble"


def publish_known_content(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Research = apps.get_model("research", "Research")
    Experience = apps.get_model("experience", "Experience")

    Project.objects.filter(slug__in=[slugify(title) for title in PROJECT_TITLES]).update(published=True)

    Research.objects.update_or_create(
        slug=slugify(RESEARCH_TITLE),
        defaults={
            "title": RESEARCH_TITLE,
            "featured": True,
            "published": True,
        },
    )

    Experience.objects.filter(
        job_title="Research Engineer",
        company="AIMS Lab, United International University",
    ).update(
        responsibilities=RESPONSIBILITIES,
        is_featured=True,
    )


def unpublish_known_content(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Research = apps.get_model("research", "Research")
    Experience = apps.get_model("experience", "Experience")

    Project.objects.filter(slug__in=[slugify(title) for title in PROJECT_TITLES]).update(published=False)
    Research.objects.filter(slug=slugify(RESEARCH_TITLE)).delete()
    Experience.objects.filter(
        job_title="Research Engineer",
        company="AIMS Lab, United International University",
    ).update(
        responsibilities="",
        is_featured=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_initial_portfolio_data"),
        ("projects", "0001_initial"),
        ("research", "0001_initial"),
        ("experience", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(publish_known_content, unpublish_known_content),
    ]
