# Generated by Django 5.2.17 on 2026-09-07 20:11

import django.db.models.deletion
from django.db import migrations, models


def seed_skill_categories(apps, schema_editor):
    Skill = apps.get_model('core', 'Skill')
    SkillCategory = apps.get_model('core', 'SkillCategory')
    SiteProfile = apps.get_model('core', 'SiteProfile')
    AboutItem = apps.get_model('core', 'AboutItem')
    labels = {
        'programming': 'Programming',
        'backend': 'Backend',
        'database': 'Databases',
        'ai_data': 'AI & Data',
        'development_tools': 'Development Tools',
    }
    for display_order, (slug, name) in enumerate(labels.items(), start=1):
        category, _created = SkillCategory.objects.get_or_create(
            slug=slug,
            defaults={'name': name, 'display_order': display_order},
        )
        Skill.objects.filter(category=slug).update(category_fk=category)
    SiteProfile.objects.get_or_create(
        name='Md. Naimuzzaman Fahim',
        defaults={
            'professional_title': 'Software Engineer',
            'tagline': 'I build web applications, backend systems, APIs, AI-powered applications and data-driven solutions.',
            'about_headline': 'Software engineering with a practical backend and data focus.',
            'about_description': 'I am a Computer Science graduate from BRAC University focused on software engineering, backend development, AI-powered applications, data analysis, machine learning, research and practical problem solving.',
            'is_active': True,
        },
    )
    about_items = [
        ('Education', 'BRAC University'),
        ('Focus', 'Software Engineering'),
        ('Primary Stack', 'Python / Django'),
        ('Interests', 'Backend Systems / AI / Data'),
    ]
    for display_order, (title, value) in enumerate(about_items, start=1):
        AboutItem.objects.get_or_create(
            title=title,
            defaults={'value': value, 'display_order': display_order, 'is_active': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_publish_known_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('value', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=120)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile/')),
                ('professional_title', models.CharField(default='Software Engineer', max_length=160)),
                ('tagline', models.TextField(blank=True)),
                ('about_headline', models.CharField(blank=True, max_length=220)),
                ('about_description', models.TextField(blank=True)),
                ('footer_message', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site profile',
                'verbose_name_plural': 'site profile',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'skill categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='category_fk',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='legacy_skills',
                to='core.skillcategory',
            ),
        ),
        migrations.RunPython(seed_skill_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='skill',
            name='category_fk',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='legacy_skills',
                to='core.skillcategory',
            ),
        ),
        migrations.RemoveField(model_name='skill', name='category'),
        migrations.RenameField(model_name='skill', old_name='category_fk', new_name='category'),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='skills',
                to='core.skillcategory',
            ),
        ),
    ]
