# Generated by Django 5.2.17 on 2026-09-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_skill_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='icon',
            new_name='icon_url_from_font_awesome',
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon_url_from_font_awesome',
            field=models.CharField(blank=True, help_text='Paste Font Awesome markup, for example: <i class="fa-brands fa-github"></i>', max_length=180),
        ),
    ]
