# Generated by Django 5.2.17 on 2026-09-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_sociallink_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='icon_url_from_font_awesome',
            field=models.CharField(blank=True, help_text='Paste Font Awesome markup, for example: <i class="fa-brands fa-github"></i>', max_length=180, verbose_name='Icon URL from Font Awesome'),
        ),
    ]
