# Generated by Django 5.2.17 on 2026-09-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('abstract', models.TextField(blank=True)),
                ('methodology', models.TextField(blank=True)),
                ('results', models.TextField(blank=True)),
                ('contribution', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='research/')),
                ('publication_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('technologies', models.ManyToManyField(blank=True, related_name='research_items', to='projects.technology')),
            ],
            options={
                'verbose_name_plural': 'research',
                'ordering': ['-date', 'title'],
            },
        ),
    ]
